### PR TITLE
Removed white space char that breaks validation

### PR DESCRIPTION
**Pull request by soluml**
The extra newline char between &lt;?xml version="1.0" encoding="UTF-8"?&gt; and the &lt;rss&gt; tag breaks what would otherwise be a valid feed.  It's only there for aesthetic reasons anyway so it should be removed.

http://validator.w3.org/feed/check.cgi

### CODE REVIEW

**Comment by dylang** [comment]
Good idea, thanks! Can you fix the tests too? Look in `/test/expectedOutput`.

**Comment by soluml** [comment]
Sure thing, I honestly didn't expect the tests to fail with such a little change :)

**Comment by soluml** [comment]
There we go, Github editor was throwing in spaces at the end of the files.  Pulled it down, edited, and it's passing now.

**Comment by soluml** [comment]
Wanted to follow up on this. Any idea on when this can be added?

**Comment by dylang** [comment]
Sorry this took so long!

**Pull request merged**
